# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 17:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Joint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=50)),
                ('shop_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('opening_time', models.TimeField(null=True)),
                ('closing_time', models.TimeField(null=True)),
                ('closed_day', models.CharField(max_length=15)),
                ('latt', models.DecimalField(decimal_places=50, max_digits=100, null=True)),
                ('longg', models.DecimalField(decimal_places=50, max_digits=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Joint_Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('car_joint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Car_Joint')),
            ],
        ),
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('carbrandid', models.AutoField(primary_key=True, serialize=False)),
                ('car_brand', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('modelid', models.AutoField(primary_key=True, serialize=False)),
                ('car_model', models.CharField(blank=True, max_length=50, null=True)),
                ('carmodel_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.CarBrands')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_Allocation_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('current_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joint_Allocation_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('current_count', models.IntegerField()),
                ('car_joint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Car_Joint')),
            ],
        ),
        migrations.CreateModel(
            name='Joint_Driver_Mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_active', models.BooleanField(default=True)),
                ('car_joint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Car_Joint')),
            ],
        ),
        migrations.CreateModel(
            name='Joint_Service_Mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_slot_count', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('car_joint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Car_Joint')),
            ],
        ),
        migrations.CreateModel(
            name='NewWashRequest',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('carmodel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.CarModels')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(max_length=50)),
                ('car_joint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Car_Joint')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('geo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Geography')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=30)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('geo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Geography')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('joint_mobile', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message=' Enter a Valid Mobile Number', regex='^(\\+?\\d{1,4}[\\s-])?(?!0+\\s+,?$)\\d{10}\\s*,?$')])),
                ('access_token', models.CharField(default='', max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line1', models.CharField(default='', max_length=100)),
                ('line2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('latt', models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True)),
                ('longg', models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('carbrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Universal.CarBrands')),
                ('carmodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Universal.CarModels')),
                ('carownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.User')),
            ],
        ),
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carwashtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Universal.User_Type'),
        ),
        migrations.AddField(
            model_name='request_allocation',
            name='service_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Service_Type'),
        ),
        migrations.AddField(
            model_name='request',
            name='time_slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.TimeSlot'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.UserCar'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.User'),
        ),
        migrations.AddField(
            model_name='newwashrequest',
            name='requesterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.User'),
        ),
        migrations.AddField(
            model_name='newwashrequest',
            name='washtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.WashType'),
        ),
        migrations.AddField(
            model_name='joint_service_mapping',
            name='service_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Service_Type'),
        ),
        migrations.AddField(
            model_name='joint_driver_mapping',
            name='driver_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.User'),
        ),
        migrations.AddField(
            model_name='joint_allocation_status',
            name='service_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Service_Type'),
        ),
        migrations.AddField(
            model_name='driver_allocation_status',
            name='driver_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.User'),
        ),
        migrations.AddField(
            model_name='driver_allocation_status',
            name='time_slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.TimeSlot'),
        ),
        migrations.AddField(
            model_name='car_joint_contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Contact_Type'),
        ),
        migrations.AddField(
            model_name='car_joint',
            name='geo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Geography'),
        ),
    ]
