# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universal', '0002_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Universal.UserStatus'),
        ),
    ]
