# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universal', '0004_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='request_allocation',
            name='current_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universal.Request_Status'),
        ),
    ]
