# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universal', '0005_auto_20160704_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_allocation',
            name='current_status',
        ),
        migrations.AddField(
            model_name='request',
            name='current_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Universal.Request_Status'),
        ),
    ]
