# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universal', '0006_auto_20160704_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='latt',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='longg',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_allocation',
            name='driver_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Universal.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(default='', max_length=400),
        ),
    ]
