# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universal', '0007_auto_20160727_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('washrating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('driverrating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('overallrating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('feedback_text', models.CharField(max_length=550)),
                ('request_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Universal.Request')),
            ],
        ),
    ]
